name: Retrieve Secret from AWS Secrets Manager

on:
  push:
    branches: [ main ]

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Retrieve secret
        id: get_secret
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id myapp/db-credentials2 --query SecretString --output text)
          echo "Secret: $SECRET"
